/**
 * Copyright 2025-2026 Blackout Secure
 * SPDX-License-Identifier: Apache-2.0
 *
 * PROJECT CONFIGURATION (MAINTAINER ONLY)
 *
 * This file contains project metadata and branding information.
 * These values are controlled by the copyright holder and should NOT be
 * modified by contributors or end users. For user-configurable settings,
 * see action.yml inputs instead.
 *
 * WARNING: Modifying these values may violate license terms and attribution
 * requirements. Only the copyright holder (Blackout Secure) should edit this file.
 */

/**
 * Project metadata and branding configuration
 * @private - For internal use only
 */
const PROJECT_CONFIG = {
  // Project identity
  name: 'Blackout Secure Robots TXT Generator',
  version: '1.0.2',
  brandingEmoji: '�',

  // Repository information
  repository: {
    url: 'github.com/blackoutsecure/bos-robotstxt-generator',
    issuesUrl: 'github.com/blackoutsecure/bos-robotstxt-generator/issues',
  },

  // Copyright and licensing
  copyrightHolder: 'Blackout Secure',
  copyrightYearStart: 2025,
  copyrightYearEnd: 2026,
  license: 'Apache License 2.0',
  spdxIdentifier: 'Apache-2.0',

  // Attribution
  generatedByComment: 'generated by Blackout Secure Robots TXT Generator',
};

/**
 * Get copyright notice
 * @returns {string} Copyright notice
 */
function getCopyrightNotice() {
  const { copyrightHolder, copyrightYearStart, copyrightYearEnd } = PROJECT_CONFIG;
  const yearRange =
    copyrightYearStart === copyrightYearEnd
      ? copyrightYearStart
      : `${copyrightYearStart}-${copyrightYearEnd}`;
  return `© ${yearRange} ${copyrightHolder}`;
}

/**
 * Get project title with branding
 * @returns {string} Branded project title
 */
function getProjectTitle() {
  return `${PROJECT_CONFIG.brandingEmoji} ${PROJECT_CONFIG.name} v${PROJECT_CONFIG.version}`;
}

/**
 * Get repository URL
 * @returns {string} Repository URL
 */
function getRepositoryUrl() {
  return `📦 ${PROJECT_CONFIG.repository.url}`;
}

/**
 * Get support/issues URL
 * @returns {string} Issues URL
 */
function getSupportUrl() {
  return `💬 Support: ${PROJECT_CONFIG.repository.issuesUrl}`;
}

/**
 * Get file generation comment
 * @param {string} fileType - Type of file (e.g., 'robots.txt')
 * @returns {string} Generation comment
 */
function getGenerationComment(fileType) {
  return `# ${fileType} ${PROJECT_CONFIG.generatedByComment}`;
}

/**
 * Get detailed generation header for robots.txt
 * @returns {string} Robots.txt comment header
 */
function getRobotsTxtHeader() {
  const {
    name,
    version,
    repository,
    copyrightHolder,
    copyrightYearStart,
    copyrightYearEnd,
    license,
    spdxIdentifier,
  } = PROJECT_CONFIG;
  const yearRange =
    copyrightYearStart === copyrightYearEnd
      ? copyrightYearStart
      : `${copyrightYearStart}-${copyrightYearEnd}`;

  return `# Generated by: ${name} v${version}
# Copyright: © ${yearRange} ${copyrightHolder}
# License: ${license}
# SPDX-License-Identifier: ${spdxIdentifier}
# Repository: https://${repository.url}
# Issues: https://${repository.issuesUrl}
# Robots Exclusion Protocol: https://www.robotstxt.org/
# RFC 9309: https://www.rfc-editor.org/rfc/rfc9309.html
# Google Guide: https://developers.google.com/search/docs/crawling-indexing/robots/intro`;
}

module.exports = {
  PROJECT_CONFIG,
  getCopyrightNotice,
  getProjectTitle,
  getRepositoryUrl,
  getSupportUrl,
  getGenerationComment,
  getRobotsTxtHeader,
};
